name: docs
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - numpy==1.18.1
  - opencv-python==4.2.0.34
  - scipy==1.6.0
  - sphinx==3.5.2
  - pytorch==1.8
  - cudatoolkit==10.2
  - pip:
    - sphinx_rtd_theme==0.5.2